broke it
zrhoffman/trafficcontrol pull request #118
Opened 2022-09-30 19:26 UTC by ocket8888

it broke now

2022-09-30 19:27 UTC, ocket8888 commented
oh, I think you need to give me permission to run actions on your repo

2022-09-30 19:31 UTC, zrhoffman commented
(approved to run)

2022-09-30 19:40 UTC, zrhoffman commented
Looking in the junit reports artifact, I don't see any tests that had failures or errors. Instead of that, maybe try replacing
https://github.com/zrhoffman/trafficcontrol/blob/e44cd0c4d3b72b672b0b9e9fc548928d34e996d3/traffic_router/core/src/test/java/org/apache/traffic_control/traffic_router/core/router/TrafficRouterTest.java#L121
with
```java
assertThat(false, equalTo(true));
```

2022-09-30 19:41 UTC, zrhoffman requested changes

2022-09-30 19:41 UTC, zrhoffman commented on traffic_router/core/src/main/java/org/apache/traffic_control/traffic_router/core/router/TrafficRouter.java
> +				throw new Exception("uh-oh!")
this is a syntax error because no semicolon

2022-09-30 19:54 UTC, ocket8888 commented
Oh, it doesn't really matter if TR doesn't build or produce test failures. Really I just wanted to see if that thing about the token went away - it did not:

![image](https://user-images.githubusercontent.com/6013378/193346586-6ab85e2c-89e0-48ed-92c6-ad2ee477acdf.png)

2022-09-30 20:01 UTC, zrhoffman commented
Would you please PR to a different branch than my PR branch so I can merge your PR?

2022-09-30 20:03 UTC, zrhoffman commented
like my master branch, you could PR to that

2022-09-30 20:04 UTC, zrhoffman commented
oh, I see what you mean now

2022-10-04 21:42 UTC, zrhoffman commented
Looks like there is a PMD error keeping the code from compiling

```java
[ERROR] /home/runner/work/trafficcontrol/trafficcontrol/traffic_router/core/src/main/java/org/apache/traffic_control/traffic_router/core/router/TrafficRouter.java:[168,4] error: unreachable statement
[ERROR] /home/runner/work/trafficcontrol/trafficcontrol/traffic_router/core/src/main/java/org/apache/traffic_control/traffic_router/core/router/TrafficRouter.java:[167,4] error: unreported exception Exception; must be caught or declared to be thrown
```

Even so, the test result summary shows up as expected on the run summary page https://github.com/zrhoffman/trafficcontrol/actions/runs/3185398456

2022-10-05 14:14 UTC, closed without merging